# General
set -g prefix C-space
set -g set-titles on
setw -g clock-mode-colour yellow
setw -g utf8 on
setw -g mode-keys vi
set -g display-panes-time 5000
set -g history-limit 5000

# Notices
set bell-action any

# Status
set -g status-right-length 30
set -g status-right "%a %b %e %I:%M %Z %Y"

# Keybinds
bind F5 set synchronize-panes
bind r respawn-window
bind m source-file ~/.tmux-main
bind space send-prefix

# Colors
set -g status-bg black
set -g status-fg green
set -g message-bg green

